name: admin-fe-ci

on:
  workflow_call:

jobs:
  ci:
    name: format, lint, build & test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install --frozen-lockfile --filter @tora-chain/admin-frontend

      - name: check-types
        working-directory: ./apps/admin-fe
        run: bun run check-types

      - name: formatting
        working-directory: ./apps/admin-fe
        run: bun run format:check

      - name: linting
        working-directory: ./apps/admin-fe
        run: bun run lint

      - name: build
        working-directory: ./apps/admin-fe
        run: bun run build

      - name: test
        working-directory: ./apps/admin-fe
        run: bun run test
