name: Auth CI

on:
  workflow_call:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: formatting
        working-directory: ./auth
        run: bun run format:check

      - name: linting
        working-directory: ./auth
        run: bun run lint
