name: main-ci

on:
  push:
    branches:
      - "**" # Runs on push to any branch

jobs:
  be-common:
    name: be-common-ci
    uses: ./.github/workflows/be-common-ci.yaml

  configs:
    name: configs-ci
    uses: ./.github/workflows/configs-ci.yaml

  specs:
    name: specs-ci
    uses: ./.github/workflows/specs-ci.yaml

  fe-common:
    name: fe-common-ci
    uses: ./.github/workflows/fe-common-ci.yaml

  ui-components:
    name: ui-components-ci
    uses: ./.github/workflows/ui-components-ci.yaml

  auth:
    name: auth-ci
    uses: ./.github/workflows/auth-ci.yaml

  backend:
    name: backend-ci
    uses: ./.github/workflows/backend-ci.yaml
    secrets: inherit

  admin-fe:
    name: admin-fe-ci
    uses: ./.github/workflows/admin-fe-ci.yaml

  auditing-fe:
    name: auditing-fe-ci
    uses: ./.github/workflows/auditing-fe-ci.yaml

  voting-fe:
    name: voting-fe-ci
    uses: ./.github/workflows/voting-fe-ci.yaml

  deploy:
    name: deploy
    needs:
      [
        be-common,
        configs,
        specs,
        fe-common,
        ui-components,
        auth,
        backend,
        admin-fe,
        auditing-fe,
        voting-fe,
      ]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
