name: main-ci

on:
  push:
    branches:
      - "**" # Runs on push to any branch

jobs:
  auth:
    name: auth-ci
    uses: ./.github/workflows/auth-ci.yaml

  backend:
    name: backend-ci
    uses: ./.github/workflows/backend-ci.yaml
    secrets: inherit

  admin-fe:
    name: admin-fe-ci
    uses: ./.github/workflows/admin-fe-ci.yaml

  auditing-fe:
    name: auditing-fe-ci
    uses: ./.github/workflows/auditing-fe-ci.yaml

  voting-fe:
    name: voting-fe-ci
    uses: ./.github/workflows/voting-fe-ci.yaml

  deploy:
    name: deploy
    needs: [auth, backend, admin-fe, auditing-fe, voting-fe]
    # if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
