name: voting-fe-ci

on:
  workflow_call:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install --frozen-lockfile --filter @tora-chain/voting-frontend

      - name: formatting
        working-directory: ./voting-fe
        run: bun run format:check

      - name: linting
        working-directory: ./voting-fe
        run: bun run lint

      - name: build
        working-directory: ./voting-fe
        run: bun run build
        env:
          NEXT_PUBLIC_AUTH_BASE: http://auth-be:8001
